services:
  web-communicator-api:
    profiles: [dev]
    volumes:
      - ./server:/app
    working_dir: /app
    command: uvicorn main:mainApp.restApi.app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1

  web-communicator-client:
    profiles: [dev]
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 3000"
    environment:
      - NODE_ENV=development  
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
