# docker-compose.devcontainer.yml
services:
  web-communicator-api:
    volumes:
      - ./server:/app
    working_dir: /app
    command: uvicorn server.main:mainApp.restApi.app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    ports:
      - "8000:8000"

  web-communicator-client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
